# Generated by Django 5.2 on 2026-03-30 17:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('processing', '处理中'), ('shipped', '已发货'), ('delivered', '已送达'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='总金额')),
                ('shipping_address', models.TextField(blank=True, verbose_name='收货地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '市场订单',
                'verbose_name_plural': '市场订单',
                'db_table': 'marketplace_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='English Name')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/categories/')),
                ('section', models.CharField(choices=[('products', '商品'), ('courses', '课程'), ('supermarket', '超市')], max_length=20, verbose_name='所属版块')),
                ('display_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplace.category')),
            ],
            options={
                'verbose_name': '市场分类',
                'verbose_name_plural': '市场分类',
                'db_table': 'marketplace_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='English Title')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='课程描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/courses/', verbose_name='封面')),
                ('instructor', models.CharField(max_length=100, verbose_name='讲师')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='时长(小时)')),
                ('lessons_count', models.PositiveIntegerField(default=0, verbose_name='课时数')),
                ('level', models.CharField(choices=[('beginner', '入门'), ('intermediate', '中级'), ('advanced', '高级'), ('all', '全部级别')], default='all', max_length=20, verbose_name='难度级别')),
                ('language', models.CharField(default='中文', max_length=50, verbose_name='教学语言')),
                ('preview_url', models.URLField(blank=True, verbose_name='预览链接')),
                ('is_featured', models.BooleanField(default=False, verbose_name='推荐课程')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否发布')),
                ('enrollment_count', models.PositiveIntegerField(default=0, verbose_name='注册人数')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='marketplace.category')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'marketplace_course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', '商品'), ('course', '课程'), ('supermarket', '超市商品')], max_length=20, verbose_name='商品类型')),
                ('item_id', models.PositiveIntegerField(verbose_name='商品ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('item_image', models.CharField(blank=True, max_length=500, verbose_name='商品图片URL')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.marketplaceorder')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'marketplace_order_item',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='English Name')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/products/', verbose_name='主图')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='marketplace/products/', verbose_name='图片2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='marketplace/products/', verbose_name='图片3')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('condition', models.CharField(choices=[('new', '全新'), ('like_new', '几乎全新'), ('used', '二手'), ('refurbished', '翻新')], default='new', max_length=20, verbose_name='状况')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='重量(kg)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='推荐商品')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.category')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'marketplace_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupermarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='English Name')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/supermarket/', verbose_name='商品图片')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('unit', models.CharField(choices=[('piece', '个'), ('kg', '公斤'), ('g', '克'), ('liter', '升'), ('ml', '毫升'), ('pack', '包'), ('box', '盒'), ('bottle', '瓶'), ('bag', '袋')], default='piece', max_length=20, verbose_name='单位')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='产地')),
                ('is_organic', models.BooleanField(default=False, verbose_name='有机食品')),
                ('is_featured', models.BooleanField(default=False, verbose_name='推荐商品')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supermarket_items', to='marketplace.category')),
            ],
            options={
                'verbose_name': '超市商品',
                'verbose_name_plural': '超市商品',
                'db_table': 'marketplace_supermarket_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
