# Generated by Django 5.2 on 2026-03-31 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='English Title')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='marketplace.course')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'db_table': 'marketplace_course_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课时标题')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='English Title')),
                ('description', models.TextField(blank=True, verbose_name='课时描述')),
                ('video_url', models.URLField(blank=True, verbose_name='视频链接')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='时长(分钟)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_free', models.BooleanField(default=False, verbose_name='免费试看')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='marketplace/course_pdfs/', verbose_name='PDF文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='marketplace.coursesection')),
            ],
            options={
                'verbose_name': '课时',
                'verbose_name_plural': '课时',
                'db_table': 'marketplace_course_lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='会话密钥')),
                ('item_type', models.CharField(choices=[('product', '商品'), ('course', '课程'), ('supermarket', '超市商品')], max_length=20, verbose_name='商品类型')),
                ('item_id', models.PositiveIntegerField(verbose_name='商品ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '购物车项目',
                'verbose_name_plural': '购物车项目',
                'db_table': 'marketplace_cart_item',
                'unique_together': {('session_key', 'item_type', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='会话密钥')),
                ('completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='marketplace.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='marketplace.courselesson')),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
                'db_table': 'marketplace_course_progress',
                'unique_together': {('session_key', 'lesson')},
            },
        ),
    ]
