# Generated by Django 5.2 on 2026-03-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_coursesection_courselesson_marketplacecartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='管理员备注'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='country',
            field=models.CharField(default='China', max_length=50, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_notes',
            field=models.TextField(blank=True, verbose_name='客户备注'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='微信/电话号码'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='payment_method',
            field=models.CharField(choices=[('wechat_pay', '微信支付'), ('alipay', '支付宝'), ('mtn_money', 'MTN Money'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('paypal', 'PayPal'), ('credit_card', '信用卡'), ('bank_transfer', '银行转账')], default='wechat_pay', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', '待支付'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('refunded', '已退款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='支付交易号'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='status',
            field=models.CharField(choices=[('pending', '待付款'), ('payment_pending', '等待付款'), ('paid', '已付款'), ('processing', '处理中'), ('shipped', '已发货'), ('delivered', '已送达'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
