# Generated by Django 5.2 on 2026-03-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplaceorder_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/course_videos/', verbose_name='视频文件'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='视频链接(外部)'),
        ),
    ]
