# Generated by Django 5.2 on 2026-03-31 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_courselesson_video_file_alter_courselesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='属性名称')),
                ('value', models.CharField(max_length=255, verbose_name='属性值')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='marketplace.product')),
            ],
            options={
                'verbose_name': '商品属性',
                'verbose_name_plural': '商品属性',
                'db_table': 'marketplace_product_attribute',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupermarketItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='属性名称')),
                ('value', models.CharField(max_length=255, verbose_name='属性值')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='marketplace.supermarketitem')),
            ],
            options={
                'verbose_name': '超市商品属性',
                'verbose_name_plural': '超市商品属性',
                'db_table': 'marketplace_supermarket_item_attribute',
                'ordering': ['name'],
            },
        ),
    ]
