# Generated by GitHub Copilot on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_add_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacecartitem',
            name='selected_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='已选属性'),
        ),
        migrations.AddField(
            model_name='marketplaceorderitem',
            name='selected_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='已选属性'),
        ),
        migrations.AlterUniqueTogether(
            name='marketplacecartitem',
            unique_together=set(),
        ),
    ]
