# Generated by Django 4.2.29 on 2026-03-31 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_delete_vendormarketplaceitem'),
        ('marketplace', '0007_course_vendor_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='manager.vendor', verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='manager.vendor', verbose_name='卖家'),
        ),
    ]
