# Generated by Django 5.2 on 2026-04-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_course_vendor_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='分类名称'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='分类名称'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True, verbose_name='课程描述'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='课程描述'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='课程描述'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='课程标题'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='课程标题'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='课程标题'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='supermarketitem',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='商品名称'),
        ),
    ]
