# Generated by Django 6.0.4 on 2026-04-30 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_category_description_en_category_description_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('item_type', models.CharField(choices=[('product', '商品'), ('course', '课程'), ('supermarket', '超市商品')], default='product', max_length=20, verbose_name='商品类型')),
                ('flash_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='秒杀价')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('stock_limit', models.PositiveIntegerField(default=100, verbose_name='限量数量')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='已售数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='marketplace.course', verbose_name='课程')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='marketplace.product', verbose_name='商品')),
                ('supermarket_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='marketplace.supermarketitem', verbose_name='超市商品')),
            ],
            options={
                'verbose_name': '秒杀活动',
                'verbose_name_plural': '秒杀活动',
                'db_table': 'marketplace_flash_sale',
                'ordering': ['end_time'],
            },
        ),
    ]
