# Generated by Django 6.0.4 on 2026-05-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_postdeliveryreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postdeliveryreview',
            new_name='marketplace_listing_b737fe_idx',
            old_name='marketplace__listing_6c8c87_idx',
        ),
    ]
