# Generated by Django 5.2 on 2026-05-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_rename_marketplace__listing_6c8c87_idx_marketplace_listing_b737fe_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarketitem',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/supermarket/', verbose_name='图片2'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/supermarket/', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='payment_method',
            field=models.CharField(choices=[('wechat_pay', '微信支付'), ('alipay', '支付宝'), ('mtn_money', 'MTN Money'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('paypal', 'PayPal'), ('credit_card', '信用卡'), ('bank_transfer', '银行转账'), ('wallet', 'Wallet')], default='wechat_pay', max_length=20, verbose_name='支付方式'),
        ),
    ]
