# Generated by Django 5.2 on 2026-05-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_supermarketitem_image_2_supermarketitem_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='库存'),
        ),
    ]
