# Generated by Django 5.2 on 2026-06-17 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_donationcampaign_and_more'),
        ('marketplace', '0019_vendor_cascade_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='manager.vendor', verbose_name='卖家'),
        ),
    ]
