# Generated by Django 6.0.4 on 2026-07-12 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_alter_emailverification_city_shipment_and_more'),
        ('marketplace', '0020_alter_course_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorderitem',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='manager.shipment', verbose_name='Expédition'),
        ),
    ]
