# Generated by Django 6.0.4 on 2026-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_marketplaceorder_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Délai de livraison — max (jours), remplace le défaut du vendeur'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Délai de livraison — min (jours), remplace le défaut du vendeur'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='delivery_days_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Délai de livraison — max (jours), remplace le défaut du vendeur'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='delivery_days_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Délai de livraison — min (jours), remplace le défaut du vendeur'),
        ),
    ]
