# Generated by Django 6.0.4 on 2026-07-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_product_delivery_days_max_product_delivery_days_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='inventory_applied',
            field=models.BooleanField(default=False, verbose_name='库存已扣减'),
        ),
    ]
