# Generated by Django 6.0.4 on 2026-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_marketplaceorder_inventory_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='payment_method',
            field=models.CharField(choices=[('wechat_pay', '微信支付'), ('alipay', '支付宝'), ('pawapay', 'PawaPay'), ('kkiapay', 'KKiaPay'), ('orange_money', 'Orange Money'), ('paypal', 'PayPal'), ('credit_card', '信用卡'), ('bank_transfer', '银行转账'), ('wallet', 'Wallet')], default='wechat_pay', max_length=20, verbose_name='支付方式'),
        ),
    ]
