# Generated by Django 6.0.4 on 2026-07-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_marketplaceorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/course_resources/', verbose_name='课时附件'),
        ),
    ]
