# Generated by Django 6.0.4 on 2026-07-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_courselesson_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/products/', verbose_name='图片4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/products/', verbose_name='图片5'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/products/videos/', verbose_name='短视频'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/supermarket/', verbose_name='图片4'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/supermarket/', verbose_name='图片5'),
        ),
        migrations.AddField(
            model_name='supermarketitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/supermarket/videos/', verbose_name='短视频'),
        ),
    ]
