# Generated by Django 6.0.4 on 2026-07-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_product_image_4_product_image_5_product_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='resource_file',
        ),
    ]
