# Generated by Django 6.0.4 on 2026-07-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0067_bookcategory_vendor'),
        ('marketplace', '0028_remove_courselesson_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_categories', to='manager.vendor', verbose_name='所属商家'),
        ),
    ]
