# Generated by Django 6.0.4 on 2026-07-20 17:20

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_category_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/categories')),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/courses'), verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/products'), verbose_name='主图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/products'), verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/products'), verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/products'), verbose_name='图片4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/products'), verbose_name='图片5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/products/videos'), verbose_name='短视频'),
        ),
        migrations.AlterField(
            model_name='supermarketitem',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/supermarket'), verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='supermarketitem',
            name='image_2',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/supermarket'), verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='supermarketitem',
            name='image_3',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/supermarket'), verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='supermarketitem',
            name='image_4',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/supermarket'), verbose_name='图片4'),
        ),
        migrations.AlterField(
            model_name='supermarketitem',
            name='image_5',
            field=models.ImageField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/supermarket'), verbose_name='图片5'),
        ),
        migrations.AlterField(
            model_name='supermarketitem',
            name='video',
            field=models.FileField(blank=True, null=True, storage=marketplace.models._marketplace_media_storage, upload_to=marketplace.models.UploadToUUID('marketplace/supermarket/videos'), verbose_name='短视频'),
        ),
    ]
