"""
DUNO 360 -- Automated deployment to fresh VPS using native SSH (no paramiko)
Run from your local machine: python deploy/deploy_new_vps.py

Prerequisites
-------------
1. Set the required environment variables before running, e.g. on Windows CMD:
     set DJANGO_SECRET_KEY=your_50char_random_key
     set DATABASE_URL=postgresql://user:pass@host:5432/db?sslmode=require
     set KKIAPAY_PUBLIC_KEY=...
     set KKIAPAY_PRIVATE_KEY=...
     set KKIAPAY_SECRET=...
     set KKIAPAY_WEBHOOK_SECRET=...
     set SUPABASE_S3_ACCESS_KEY=...
     set SUPABASE_S3_SECRET_KEY=...

2. Optional -- Cloudflare Origin Certificate (for Full-strict SSL):
     deploy/cloudflare_origin.crt   (public cert)
     deploy/cloudflare_origin.key   (private key -- NEVER commit this file)
   If not present, a self-signed cert is generated automatically.

3. Windows: ensure OpenSSH client is installed (Settings > Optional features).
   The 'ssh' command must be on PATH.
"""
import os
import sys
import time
import textwrap
import subprocess
import base64

# -- connection ---------------------------------------------------------------
HOST = "142.93.45.77"
USER = "root"

SSH_BASE = [
    "ssh",
    "-o", "StrictHostKeyChecking=no",
    "-o", "BatchMode=yes",
    "-o", "ConnectTimeout=20",
    f"{USER}@{HOST}",
]

# -- application layout -------------------------------------------------------
APP_DIR  = "/opt/duno360/app"
APP_USER = "duno360"
DOMAIN   = "duno360.com"
REPO_URL = "https://github.com/EspenQueston/book-project.git"


# -- required secrets (NO fallback defaults -- public repo!) ------------------
def _env(name: str) -> str:
    val = os.environ.get(name, "").strip()
    if not val:
        sys.exit(
            f"ERROR: required env var {name!r} is not set.\n"
            f"       Set it before running this script."
        )
    return val


SECRET_KEY          = _env("DJANGO_SECRET_KEY")
DATABASE_URL        = _env("DATABASE_URL")
KKIAPAY_PUBLIC_KEY  = _env("KKIAPAY_PUBLIC_KEY")
KKIAPAY_PRIVATE_KEY = _env("KKIAPAY_PRIVATE_KEY")
KKIAPAY_SECRET      = _env("KKIAPAY_SECRET")
KKIAPAY_WEBHOOK_SEC = _env("KKIAPAY_WEBHOOK_SECRET")
S3_ACCESS_KEY       = _env("SUPABASE_S3_ACCESS_KEY")
S3_SECRET_KEY       = _env("SUPABASE_S3_SECRET_KEY")

ENV_CONTENT = f"""# DUNO 360 production environment
# Generated by deploy_new_vps.py -- DO NOT commit this file.

DEBUG=False
SECRET_KEY={SECRET_KEY}
ALLOWED_HOSTS={DOMAIN},www.{DOMAIN},127.0.0.1,localhost
FORCE_HTTPS=True

DATABASE_URL={DATABASE_URL}

CSRF_TRUSTED_ORIGINS=https://{DOMAIN},https://www.{DOMAIN}

KKIAPAY_PUBLIC_KEY={KKIAPAY_PUBLIC_KEY}
KKIAPAY_PRIVATE_KEY={KKIAPAY_PRIVATE_KEY}
KKIAPAY_SECRET={KKIAPAY_SECRET}
KKIAPAY_SANDBOX=False
KKIAPAY_WEBHOOK_SECRET={KKIAPAY_WEBHOOK_SEC}

SUPABASE_S3_ACCESS_KEY={S3_ACCESS_KEY}
SUPABASE_S3_SECRET_KEY={S3_SECRET_KEY}
SUPABASE_S3_BUCKET=media
SUPABASE_S3_ENDPOINT=https://gebnxwsrezadwuvmqtyy.supabase.co/storage/v1/s3

NGROK_ENABLED=False
"""


# -- SSH helpers --------------------------------------------------------------
def run(cmd: str, check: bool = True) -> str:
    """Run a shell command on the remote host."""
    label = cmd[:120] + ("..." if len(cmd) > 120 else "")
    print(f"  $ {label}")
    r = subprocess.run(SSH_BASE + [cmd], capture_output=True, text=True, timeout=300)
    if r.stdout.strip():
        print(textwrap.indent(r.stdout.strip()[-600:], "    "))
    if r.returncode != 0:
        if r.stderr.strip():
            print(textwrap.indent("[err] " + r.stderr.strip()[-300:], "    "))
        if check:
            raise RuntimeError(f"Command failed (rc={r.returncode}): {label}")
    return r.stdout


def upload(remote_path: str, content: str, mode: str = "644") -> None:
    """Upload string content to a remote path via base64 over SSH."""
    b64 = base64.b64encode(content.encode("utf-8")).decode()
    # Write in 4k chunks to avoid shell argument length limits
    chunk_size = 4096
    chunks = [b64[i:i + chunk_size] for i in range(0, len(b64), chunk_size)]
    run(f"printf '%s' '{chunks[0]}' > /tmp/_up64")
    for chunk in chunks[1:]:
        run(f"printf '%s' '{chunk}' >> /tmp/_up64")
    run(
        f"base64 -d /tmp/_up64 > {remote_path}"
        f" && chmod {mode} {remote_path}"
        f" && rm /tmp/_up64"
    )
    print(f"  ^ uploaded {remote_path}")


def upload_local(local_path: str, remote_path: str, mode: str = "644") -> None:
    """Upload a local file to the remote host."""
    if not os.path.exists(local_path):
        sys.exit(f"ERROR: local file not found: {local_path}")
    with open(local_path, "r", encoding="utf-8") as fh:
        upload(remote_path, fh.read(), mode)


# -- deployment ---------------------------------------------------------------
def main() -> None:
    print("\n" + "=" * 62)
    print(f"  DUNO 360 deployment -> {HOST}")
    print("=" * 62 + "\n")

    script_dir  = os.path.dirname(os.path.abspath(__file__))
    cf_crt_path = os.path.join(script_dir, "cloudflare_origin.crt")
    cf_key_path = os.path.join(script_dir, "cloudflare_origin.key")

    # 0 -- connectivity test
    print("[0] Testing SSH connectivity ...")
    run("echo SSH_OK")

    # 1 -- system packages
    print("\n[1] Installing system packages ...")
    run(
        "export DEBIAN_FRONTEND=noninteractive && "
        "apt-get update -qq && "
        "apt-get install -y --no-install-recommends "
        "nginx git python3 python3-venv python3-dev "
        "python3-pip build-essential libpq-dev ufw curl openssl"
    )

    # 2 -- app user + dirs
    print("\n[2] Creating app user and directories ...")
    run(
        f"id -u {APP_USER} &>/dev/null || "
        f"useradd --system --home {APP_DIR} --shell /bin/bash {APP_USER}"
    )
    run(f"mkdir -p {APP_DIR} /opt/duno360")
    run(f"chown -R {APP_USER}:{APP_USER} /opt/duno360")

    # 3 -- clone/update repo
    print("\n[3] Cloning repository ...")
    exists = run(f"test -d {APP_DIR}/.git && echo yes || echo no", check=False).strip()
    if "yes" in exists:
        run(f"cd {APP_DIR} && sudo -u {APP_USER} git pull")
    else:
        run(f"sudo -u {APP_USER} git clone {REPO_URL} {APP_DIR}")

    # 4 -- Python venv
    print("\n[4] Setting up Python virtualenv ...")
    run(f"sudo -u {APP_USER} python3 -m venv {APP_DIR}/.venv")
    run(f"sudo -u {APP_USER} {APP_DIR}/.venv/bin/pip install --upgrade --quiet pip wheel")
    run(
        f"sudo -u {APP_USER} {APP_DIR}/.venv/bin/pip install "
        f"--quiet -r {APP_DIR}/requirements.txt"
    )

    # 5 -- .env
    print("\n[5] Writing production .env ...")
    run("mkdir -p /opt/duno360")
    upload("/opt/duno360/.env", ENV_CONTENT, mode="600")
    run(f"chown {APP_USER}:{APP_USER} /opt/duno360/.env")
    run(f"ln -sf /opt/duno360/.env {APP_DIR}/.env")

    # 6 -- Django management commands
    print("\n[6] Django migrate + collectstatic ...")
    py  = f"{APP_DIR}/.venv/bin/python"
    mgr = f"cd {APP_DIR} && sudo -u {APP_USER} {py} manage.py"
    run(f"{mgr} migrate --noinput")
    run(f"{mgr} collectstatic --noinput --clear")

    # 7 -- systemd service
    print("\n[7] Creating systemd service ...")
    svc = textwrap.dedent(f"""\
        [Unit]
        Description=DUNO 360 Django App
        After=network.target

        [Service]
        User={APP_USER}
        Group={APP_USER}
        WorkingDirectory={APP_DIR}
        EnvironmentFile=/opt/duno360/.env
        ExecStart={APP_DIR}/.venv/bin/gunicorn \\
            --config {APP_DIR}/gunicorn.conf.py \\
            book_Project.wsgi:application
        Restart=on-failure
        RestartSec=5
        StandardOutput=journal
        StandardError=journal

        [Install]
        WantedBy=multi-user.target
    """)
    upload("/etc/systemd/system/duno360.service", svc)
    run("systemctl daemon-reload")
    run("systemctl enable duno360")
    run("systemctl restart duno360")
    time.sleep(3)
    run("systemctl is-active duno360", check=False)

    # 8 -- TLS certificate
    print("\n[8] Installing TLS certificate ...")
    run("mkdir -p /etc/nginx/ssl")
    if os.path.exists(cf_crt_path) and os.path.exists(cf_key_path):
        upload_local(cf_crt_path, "/etc/nginx/ssl/duno360.crt", mode="644")
        upload_local(cf_key_path, "/etc/nginx/ssl/duno360.key", mode="600")
        print("    Cloudflare Origin Certificate installed.")
    else:
        print(f"    CF cert not found at {script_dir}/cloudflare_origin.{{crt,key}}")
        print("    Generating self-signed certificate (replace later with CF Origin Cert)...")
        run(
            "openssl req -x509 -nodes -days 365 -newkey rsa:2048 "
            "-keyout /etc/nginx/ssl/duno360.key "
            "-out /etc/nginx/ssl/duno360.crt "
            f'-subj "/CN={DOMAIN}"'
        )

    # 9 -- Nginx config
    print("\n[9] Configuring Nginx ...")
    nginx = textwrap.dedent(f"""\
        # HTTP -> HTTPS redirect
        server {{
            listen 80;
            server_name {DOMAIN} www.{DOMAIN};
            return 301 https://$host$request_uri;
        }}

        server {{
            listen 443 ssl http2;
            server_name {DOMAIN} www.{DOMAIN};

            ssl_certificate     /etc/nginx/ssl/duno360.crt;
            ssl_certificate_key /etc/nginx/ssl/duno360.key;
            ssl_protocols       TLSv1.2 TLSv1.3;
            ssl_ciphers         HIGH:!aNULL:!MD5;
            ssl_prefer_server_ciphers on;

            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header X-Frame-Options SAMEORIGIN always;
            add_header X-Content-Type-Options nosniff always;
            add_header Referrer-Policy strict-origin-when-cross-origin always;
            add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;

            client_max_body_size 10M;

            location /static/ {{
                alias {APP_DIR}/staticfiles/;
                expires 30d;
                add_header Cache-Control "public, max-age=2592000";
            }}

            location /media/ {{
                alias {APP_DIR}/media/;
                expires 7d;
            }}

            location / {{
                proxy_pass         http://127.0.0.1:8000;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_read_timeout 120s;
                proxy_connect_timeout 10s;
            }}
        }}
    """)
    upload("/etc/nginx/sites-available/duno360", nginx)
    run("ln -sf /etc/nginx/sites-available/duno360 /etc/nginx/sites-enabled/duno360")
    run("rm -f /etc/nginx/sites-enabled/default")
    run("nginx -t")
    run("systemctl reload nginx")

    # 10 -- firewall
    print("\n[10] Configuring UFW ...")
    run("ufw allow OpenSSH")
    run("ufw allow 'Nginx Full'")
    run("ufw --force enable")

    # smoke test
    print("\n[v] Smoke test ...")
    out = run(
        "curl -sI --max-time 10 http://127.0.0.1:8000/manager/ | head -3",
        check=False
    )
    if any(x in out for x in ("200", "301", "302")):
        print("    Gunicorn is responding.")
    else:
        print("    WARNING: unexpected Gunicorn response.")
        print("    Check with: journalctl -u duno360 -n 50")

    print(
        "\n" + "=" * 62 + "\n"
        f"  Deployment complete!\n"
        f"  URL: https://{DOMAIN}\n\n"
        f"  Next steps:\n"
        f"    1. Cloudflare DNS -> A record {DOMAIN} = {HOST}  (Proxied ON)\n"
        f"    2. Cloudflare SSL -> Full (strict)  [if CF Origin Cert was used]\n\n"
        f"  Useful server commands:\n"
        f"    journalctl -u duno360 -f\n"
        f"    systemctl status nginx\n"
        f"    systemctl restart duno360\n"
        + "=" * 62
    )


if __name__ == "__main__":
    main()
