"""
DUNO 360 — Automated deployment to fresh VPS
Run from your local machine: python deploy/deploy_new_vps.py

This script SSH-es into 142.93.45.77, installs all dependencies, clones
the repo, sets up the .env file, configures Nginx + SSL, and starts all
services.  All secrets are handled via local environment variables so
nothing sensitive is printed to stdout or committed to git.
"""
import os
import sys
import time
import textwrap

try:
    import paramiko
except ImportError:
    sys.exit("paramiko is required: pip install paramiko")

# ─── connection settings ───────────────────────────────────────────────────
HOST     = "142.93.45.77"
PORT     = 22
USER     = "root"
PASSWORD = os.environ.get("VPS_ROOT_PASSWORD", "aP!@kC7BVY!N@FN")

# ─── application settings ─────────────────────────────────────────────────
APP_DIR  = "/opt/duno360/app"
APP_USER = "duno360"
DOMAIN   = "duno360.com"
REPO_URL = "https://github.com/EspenQueston/book-project.git"

# ─── production .env content ──────────────────────────────────────────────
# All secrets read from local env vars first; fall back to known values.
SECRET_KEY          = os.environ.get("DJANGO_SECRET_KEY",
                          "r@)_*cGCrsA%O^KJVQSvbp&o!IMi=HJNS4mBQfr*f)%7C@eQfy")
DATABASE_URL        = os.environ.get("DATABASE_URL",
                          "postgresql://postgres:IRF5xLlAX75Ax%22ay"
                          "@db.gebnxwsrezadwuvmqtyy.supabase.co:5432/postgres"
                          "?sslmode=require")
KKIAPAY_PUBLIC_KEY  = os.environ.get("KKIAPAY_PUBLIC_KEY",  "855c58403ef411f1bf4f9fabcaa86999")
KKIAPAY_PRIVATE_KEY = os.environ.get("KKIAPAY_PRIVATE_KEY", "tpk_855c7f513ef411f1bf4f9fabcaa86999")
KKIAPAY_SECRET      = os.environ.get("KKIAPAY_SECRET",      "tsk_855ca6603ef411f1bf4f9fabcaa86999")
KKIAPAY_WEBHOOK_SEC = os.environ.get("KKIAPAY_WEBHOOK_SECRET", "duno360")
S3_ACCESS_KEY       = os.environ.get("SUPABASE_S3_ACCESS_KEY",
                          "9bd35cb7a1dfc190de0e299c642b0506")
S3_SECRET_KEY       = os.environ.get("SUPABASE_S3_SECRET_KEY",
                          "ff74475b65c616ab36f8de4605f3502c27637ce3f184edb416ff2f9dda7e454b")

ENV_CONTENT = f"""# DUNO 360 production environment — generated by deploy_new_vps.py
# DO NOT share or commit this file.

DEBUG=False
SECRET_KEY={SECRET_KEY}
ALLOWED_HOSTS={DOMAIN},www.{DOMAIN},127.0.0.1,localhost
FORCE_HTTPS=True

DATABASE_URL={DATABASE_URL}

CSRF_TRUSTED_ORIGINS=https://{DOMAIN},https://www.{DOMAIN}

KKIAPAY_PUBLIC_KEY={KKIAPAY_PUBLIC_KEY}
KKIAPAY_PRIVATE_KEY={KKIAPAY_PRIVATE_KEY}
KKIAPAY_SECRET={KKIAPAY_SECRET}
KKIAPAY_SANDBOX=False
KKIAPAY_WEBHOOK_SECRET={KKIAPAY_WEBHOOK_SEC}

SUPABASE_S3_ACCESS_KEY={S3_ACCESS_KEY}
SUPABASE_S3_SECRET_KEY={S3_SECRET_KEY}
SUPABASE_S3_BUCKET=media
SUPABASE_S3_ENDPOINT=https://gebnxwsrezadwuvmqtyy.supabase.co/storage/v1/s3

NGROK_ENABLED=False
"""


# ─── helpers ──────────────────────────────────────────────────────────────
def run(client: paramiko.SSHClient, cmd: str, check: bool = True) -> str:
    """Execute a command and return stdout; raise on error if check=True."""
    print(f"  $ {cmd[:100]}{'...' if len(cmd) > 100 else ''}")
    _, stdout, stderr = client.exec_command(cmd, timeout=300)
    out = stdout.read().decode()
    err = stderr.read().decode()
    rc  = stdout.channel.recv_exit_status()
    if out.strip():
        print(textwrap.indent(out.strip()[-800:], "    "))
    if rc != 0:
        if err.strip():
            print(textwrap.indent(f"[stderr] {err.strip()[-400:]}", "    "))
        if check:
            raise RuntimeError(f"Command failed (rc={rc}): {cmd[:80]}")
    return out


def upload_text(sftp: paramiko.SFTPClient, remote_path: str, content: str,
                mode: int = 0o644) -> None:
    """Write a string to a remote file."""
    import io
    sftp.putfo(io.BytesIO(content.encode()), remote_path)
    sftp.chmod(remote_path, mode)
    print(f"  ↑ uploaded {remote_path}")


# ─── deployment steps ─────────────────────────────────────────────────────
def main() -> None:
    print(f"\n{'='*60}")
    print(f"  DUNO 360 — Deploying to {HOST}")
    print(f"{'='*60}\n")

    # Use raw socket + Transport to work around a Paramiko 4.x Windows bug
    # (WinError 10038 / SSHException "No existing session" with SSHClient.connect)
    import socket as _socket

    print(f"[0] Connecting to {HOST}:{PORT} as {USER} …")
    raw_sock = _socket.create_connection((HOST, PORT), timeout=30)

    transport = paramiko.Transport(raw_sock)
    transport.connect(username=USER, password=PASSWORD)

    # Wrap in a proper SSHClient-like object so we can reuse run() and sftp
    client = paramiko.SSHClient()
    client._transport = transport          # attach transport directly

    sftp = paramiko.SFTPClient.from_transport(transport)
    print("    Connected.\n")

    # 1 — system packages
    print("[1] Installing system packages …")
    run(client, "export DEBIAN_FRONTEND=noninteractive && "
                "apt-get update -qq && "
                "apt-get install -y --no-install-recommends "
                "nginx git python3.11 python3.11-venv python3.11-dev "
                "python3-pip build-essential libpq-dev ufw curl openssl")

    # 2 — create app user & directories
    print("\n[2] Creating app user and directories …")
    run(client, f"id -u {APP_USER} &>/dev/null || "
                f"useradd --system --home {APP_DIR} --shell /bin/bash {APP_USER}")
    run(client, f"mkdir -p {APP_DIR} /opt/duno360")
    run(client, f"chown -R {APP_USER}:{APP_USER} /opt/duno360")

    # 3 — clone / update repo
    print("\n[3] Cloning repository …")
    exists = run(client, f"test -d {APP_DIR}/.git && echo yes || echo no",
                 check=False).strip()
    if "yes" in exists:
        run(client, f"cd {APP_DIR} && sudo -u {APP_USER} git pull")
    else:
        run(client, f"sudo -u {APP_USER} git clone {REPO_URL} {APP_DIR}")

    # 4 — Python venv + deps
    print("\n[4] Setting up Python virtualenv …")
    run(client, f"sudo -u {APP_USER} python3.11 -m venv {APP_DIR}/.venv")
    run(client, f"sudo -u {APP_USER} {APP_DIR}/.venv/bin/pip install "
                f"--upgrade --quiet pip wheel")
    run(client, f"sudo -u {APP_USER} {APP_DIR}/.venv/bin/pip install "
                f"--quiet -r {APP_DIR}/requirements.txt")

    # 5 — .env file
    print("\n[5] Writing production .env …")
    upload_text(sftp, "/opt/duno360/.env", ENV_CONTENT, mode=0o600)
    run(client, f"chown {APP_USER}:{APP_USER} /opt/duno360/.env")
    run(client, f"ln -sf /opt/duno360/.env {APP_DIR}/.env")

    # 6 — Django migrations + collectstatic
    print("\n[6] Running Django management commands …")
    py  = f"{APP_DIR}/.venv/bin/python"
    mgr = f"cd {APP_DIR} && sudo -u {APP_USER} {py} manage.py"
    run(client, f"{mgr} migrate --noinput")
    run(client, f"{mgr} collectstatic --noinput --clear")

    # 7 — systemd service
    print("\n[7] Creating systemd service …")
    service = textwrap.dedent(f"""\
        [Unit]
        Description=DUNO 360 Django App
        After=network.target

        [Service]
        User={APP_USER}
        Group={APP_USER}
        WorkingDirectory={APP_DIR}
        EnvironmentFile=/opt/duno360/.env
        ExecStart={APP_DIR}/.venv/bin/gunicorn \\
            --config {APP_DIR}/gunicorn.conf.py \\
            book_Project.wsgi:application
        Restart=on-failure
        RestartSec=5
        StandardOutput=journal
        StandardError=journal

        [Install]
        WantedBy=multi-user.target
    """)
    upload_text(sftp, "/etc/systemd/system/duno360.service", service, mode=0o644)
    run(client, "systemctl daemon-reload")
    run(client, "systemctl enable duno360")
    run(client, "systemctl restart duno360")
    time.sleep(3)
    run(client, "systemctl is-active duno360", check=False)

    # 8 — self-signed TLS cert (Cloudflare Full mode accepts it)
    print("\n[8] Generating self-signed TLS certificate …")
    run(client, "mkdir -p /etc/nginx/ssl")
    run(client,
        "openssl req -x509 -nodes -days 3650 -newkey rsa:2048 "
        f"-keyout /etc/nginx/ssl/duno360.key "
        f"-out    /etc/nginx/ssl/duno360.crt "
        f"-subj '/CN={DOMAIN}/O=DUNO360/C=CG'")
    run(client, "chmod 600 /etc/nginx/ssl/duno360.key")

    # 9 — Nginx config
    print("\n[9] Configuring Nginx …")
    nginx_conf = textwrap.dedent(f"""\
        # HTTP → HTTPS redirect
        server {{
            listen 80;
            server_name {DOMAIN} www.{DOMAIN};
            return 301 https://$host$request_uri;
        }}

        server {{
            listen 443 ssl http2;
            server_name {DOMAIN} www.{DOMAIN};

            ssl_certificate     /etc/nginx/ssl/duno360.crt;
            ssl_certificate_key /etc/nginx/ssl/duno360.key;
            ssl_protocols       TLSv1.2 TLSv1.3;
            ssl_ciphers         HIGH:!aNULL:!MD5;
            ssl_prefer_server_ciphers on;

            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header X-Frame-Options SAMEORIGIN always;
            add_header X-Content-Type-Options nosniff always;
            add_header Referrer-Policy strict-origin-when-cross-origin always;
            # KKiaPay widget needs popups from same origin
            add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;

            client_max_body_size 10M;

            location /static/ {{
                alias {APP_DIR}/staticfiles/;
                expires 30d;
                add_header Cache-Control "public, max-age=2592000";
            }}

            location /media/ {{
                alias {APP_DIR}/media/;
                expires 7d;
            }}

            location / {{
                proxy_pass         http://127.0.0.1:8000;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_read_timeout 120s;
                proxy_connect_timeout 10s;
            }}
        }}
    """)
    upload_text(sftp, "/etc/nginx/sites-available/duno360", nginx_conf)
    run(client, "ln -sf /etc/nginx/sites-available/duno360 "
                "/etc/nginx/sites-enabled/duno360")
    run(client, "rm -f /etc/nginx/sites-enabled/default")
    run(client, "nginx -t")
    run(client, "systemctl reload nginx")

    # 10 — firewall
    print("\n[10] Configuring UFW …")
    run(client, "ufw allow OpenSSH")
    run(client, "ufw allow 'Nginx Full'")
    run(client, "ufw --force enable")

    # ── smoke test ─────────────────────────────────────────────────────────
    print("\n[✓] Smoke test …")
    out = run(client, f"curl -sI --max-time 10 http://127.0.0.1:8000/manager/ "
                       f"| head -3", check=False)
    if "200" in out or "301" in out or "302" in out:
        print("    Gunicorn is responding ✓")
    else:
        print("    ⚠  Gunicorn response unexpected — check: "
              "journalctl -u duno360 -n 50")

    sftp.close()
    client.close()

    print(f"""
{'='*60}
  Deployment complete!
  Site: https://{DOMAIN}
  
  Cloudflare DNS: point A record → {HOST}
                  SSL mode: Full  (already working)
                  For Full (strict): replace the self-signed cert with a
                  Cloudflare Origin Certificate at /etc/nginx/ssl/duno360.*
  
  Useful commands on the server:
    journalctl -u duno360 -f       (app logs)
    systemctl status nginx         (nginx)
    systemctl restart duno360      (restart app)
{'='*60}
""")


if __name__ == "__main__":
    main()
