#!/usr/bin/env python3
"""
fix_ssl.py - Run on VPS as root to install Cloudflare Origin Certificate,
configure Nginx for HTTPS, run Django migrations, and restart the service.

Usage (from DigitalOcean console):
    cd /opt/duno360/app && git pull origin main && python3 deploy/fix_ssl.py
"""
import hashlib
import os
import re
import subprocess
import sys
import time
import urllib.request

# ─── Cloudflare Origin Certificate (new, valid for duno360.com) ──────────────
CERT = """\
-----BEGIN CERTIFICATE-----
MIIEojCCA4qgAwIBAgIUUYsYoBea8pkTVHwbLgYxb3KZ3TwwDQYJKoZIhvcNAQEL
BQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw
MgYDVQQLEytDbG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y
aXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh
MB4XDTI2MDUxMDE5NDYwMFoXDTQxMDUwNjE5NDYwMFowYjEZMBcGA1UEChMQQ2xv
dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
BgNVBAMTHUNsb3VkZmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3WdGSBDO2dS3cYA0/tE/P7PoFPGY+z+otjbM
SzJxvR782KgqERBV9FROfBhPi6Pj+TS/Uog13fmWX43POxRMtaFQoWCUzCito89t
gsVGkEG75VseN90zcHbxj4ZBkcFyqI6QnErkonGOBUq6AYG2gU9JsI6fFuodTgP/
r/iBpzs0WKUVR6vndWrwJConNCBi/8UIjOUSEqJZpkReLZD46SBXzTCY0oRXntO2
PcmcJ9UrJXlh9c8AlG6FlogpIU3M1JefHY7fND1S/miFB6IvN6CnMwQCE7c8yCOU
0uB7eI84HpAuCAMkcyUN9C47Q/FfvvFE7KIV2rODRCaItkCIOwIDAQABo4IBJDCC
ASAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBT+oEQOtIHbJoYYBEnS6fEVPeWWgTAf
BgNVHSMEGDAWgBQk6FNXXXw0QIep65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIw
MAYIKwYBBQUHMAGGJGh0dHA6Ly9vY3NwLmNsb3VkZmxhcmUuY29tL29yaWdpbl9j
YTAlBgNVHREEHjAcgg0qLmR1bm8zNjAuY29tggtkdW5vMzYwLmNvbTA4BgNVHR8E
MTAvMC2gK6AphidodHRwOi8vY3JsLmNsb3VkZmxhcmUuY29tL29yaWdpbl9jYS5j
cmwwDQYJKoZIhvcNAQELBQADggEBAJiA7lUKQuzg/ZT2o5sQvJ+ly+/WntwU9wbM
mul+CDPpyKfykw/NCF4FMVnUD6XVv9XHm+7RmepFZPp+R/Owr7S7EifjqKOc2NfS
Lr4YlCkFSj29K68ryAn7Uze7oN+1fHV6UV0eqy6Fgb4GEB9OOJV+N5O4Ziw28Zpd
2SwUsQIEyYIPHdOwv1L6inI3hG/bD9J+0DZywUf/I0x1RJSw8Ve7rwFXgqmCiBMu
34I0S87WS8MZB4jALw2+Mv5rjJPQ6MZ/XTyEgOE8+F8+vu8AAOmYuwn9hx/5wKhb
ehZ8gKvxGKSpn9O2UI7wdPCixbI6rAEJ3CqIjNhWpkcgac4h8XM=
-----END CERTIFICATE-----
"""

KEY = """\
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDdZ0ZIEM7Z1Ldx
gDT+0T8/s+gU8Zj7P6i2NsxLMnG9HvzYqCoREFX0VE58GE+Lo+P5NL9SiDXd+ZZf
jc87FEy1oVChYJTMKK2jz22CxUaQQbvlWx433TNwdvGPhkGRwXKojpCcSuSicY4F
SroBgbaBT0mwjp8W6h1OA/+v+IGnOzRYpRVHq+d1avAkKic0IGL/xQiM5RISolmm
RF4tkPjpIFfNMJjShFee07Y9yZwn1SsleWH1zwCUboWWiCkhTczUl58djt80PVL+
aIUHoi83oKczBAITtzzII5TS4Ht4jzgekC4IAyRzJQ30LjtD8V++8UTsohXas4NE
Joi2QIg7AgMBAAECggEAJzQUvUkAn5CrZNUbTS2XAfwksaSv/nkgshcU6JHHkwHM
Kr7oJ/pZBfjxpsaVOzgrc2KUKBSHWUVLC6NsGN140cZ9JP4Ziub/DBz8GqY83ulM
0IloWeL4q0bcchoHPTxgRZls4MfgISVzTNuVARRLUS1Nco5mfCO7SaeqnCmoJ4if
ZHLIvRWRWIFkFut/sxLiZizYWL7HY+byRJMs/Kf8jFn8VvDYA903dq+aN7pNT2Ug
dEVwwWngxFbyDN4Cel2RGfDD+9f//j2ztCkGpFGZhA6ogXCBF/N71N+2J/LsyJ0+
/lsaX5xquIXUOFt3vwmYd7YjWkWp11rikrnF/PdIRQKBgQDw2rmtbm5pRUPmHx0X
ZoVUZvB2Ge5gKFBQyqAJz0IQ8soJZ07P4zIjOkcS0yX14UCI4SPsZQc6c2uvdSq3
vph5GDf7cnq02MPsRhsn3mamsHJ94TOx9LZYhl/4x2UOebsaRaDU9BwmTzshkgXn
SernIbI1PJ9xspMVbA2GAqQoTQKBgQDrU21keevknOqGfRzjLzL3MIjOHAVUPiol
SEeWFDre6PfASVTuH8WNIgZWMqZGHCu9bPA2YHFs7xVsvaljp93f9nCEaAEkVy3e
HShGETbnfqDJMG+kvu2/fD7LUReKyYIHBg6w1E6JdtDQMnhFzX/1K+twnKbmiT4c
6b/ZRFI2pwKBgQCkAh0b9y3iK1NwGVHDBIHYFny5vzCuc+U1DrVp2KNBTUK8oodt
UmVqzZ1mOTgJNcivLLg8mhMQ/1Wd1egv1O6YzyAX7j2WdmD7vEVzoaM+8LoV88sy
69Nbdq1Vh9nNwKDi4/T/7fZZM+ytEHVKqO/3Ud+7FrvwPUyg8sJGtfe4pQKBgHzU
CFcgBW2DfzRP8Z7hTpuo9yi93GXPg/O6355QpNnRonoxbAfUeqpevhXDUEgocVtO
Ci4OApzSRf8krFHcnelLhGv374Mja4VC2jYws3sgxJF0TASL8vl8IqMfJOnN8ldf
czOBqxdoG2QVIY+FbrbS0VUvA6mOa5BSvh22DBZJAoGAYQKFozUbQBsYCnJtFcdK
UKsi8YgwHOnvnpPgNMd94IJTcdU2OzHoLRy7wd6h5whLNjKmEDg6x8jNkuCZYb4h
90HBBm/TmNIpReeLGFSfOT4iQ5EEUUiJ/JwM2PzK0Kqo41wcD1OdEqtMlANMJtjV
k6acdnjrhLPR0HkY5W+zY1c=
-----END PRIVATE KEY-----
"""

NGINX_CONF = """\
# duno360.com - generated by deploy/fix_ssl.py
server {
    listen 80;
    server_name duno360.com www.duno360.com 159.203.186.103;
    return 301 https://duno360.com$request_uri;
}

server {
    listen 443 ssl;
    server_name duno360.com www.duno360.com;

    ssl_certificate     /etc/ssl/cloudflare/duno360.com.fullchain.pem;
    ssl_certificate_key /etc/ssl/cloudflare/duno360.com.key;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    client_max_body_size 512M;

    location /static/ {
        alias /var/www/duno360/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /var/www/duno360/media/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass          http://127.0.0.1:8000;
        proxy_set_header    Host              $host;
        proxy_set_header    X-Real-IP         $remote_addr;
        proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto https;
        proxy_read_timeout  120s;
        proxy_connect_timeout 10s;
    }
}
"""

ENV_FILE = '/opt/duno360/.env'
APP_DIR  = '/opt/duno360/app'
VENV     = '/opt/duno360/app/.venv/bin/python'
SSL_DIR  = '/etc/ssl/cloudflare'
NGINX_AVAILABLE = '/etc/nginx/sites-available/duno360'
NGINX_ENABLED   = '/etc/nginx/sites-enabled/duno360'


def run(cmd, check=True, capture=False, cwd=None, env=None):
    kw = dict(shell=True, cwd=cwd, env=env)
    if capture:
        kw['capture_output'] = True
        kw['text'] = True
    r = subprocess.run(cmd, **kw)
    if check and r.returncode != 0:
        if capture:
            print('STDERR:', r.stderr[-500:])
        print(f'Command failed (exit {r.returncode}): {cmd}')
    return r


def md5(s):
    return hashlib.md5(s.strip().encode()).hexdigest()


def step(msg):
    print(f'\n{"─"*60}')
    print(f'  {msg}')
    print('─'*60)


# ── 1. Write certificate and key ─────────────────────────────────────────────
step('1/7  Writing TLS certificate and private key')

os.makedirs(SSL_DIR, mode=0o700, exist_ok=True)

cert_path = f'{SSL_DIR}/duno360.com.pem'
key_path  = f'{SSL_DIR}/duno360.com.key'
fc_path   = f'{SSL_DIR}/duno360.com.fullchain.pem'

with open(cert_path, 'w') as f:
    f.write(CERT)
os.chmod(cert_path, 0o644)

with open(key_path, 'w') as f:
    f.write(KEY)
os.chmod(key_path, 0o600)

print(f'Cert: {len(CERT)} bytes → {cert_path}')
print(f'Key:  {len(KEY)} bytes → {key_path}')


# ── 2. Verify cert/key match ─────────────────────────────────────────────────
step('2/7  Verifying cert/key pair')

rc = run(f'openssl x509 -noout -modulus -in {cert_path}', capture=True)
rk = run(f'openssl rsa  -noout -modulus -in {key_path}',  capture=True)

if rc.returncode != 0 or rk.returncode != 0:
    print('ERROR: openssl could not read cert or key!')
    sys.exit(1)

cm, km = md5(rc.stdout), md5(rk.stdout)
if cm != km:
    print(f'CERT mod: {cm}')
    print(f'KEY  mod: {km}')
    print('ERROR: Certificate and private key DO NOT MATCH!')
    sys.exit(1)

print('✅ Cert/Key MATCH')

# Print cert info
info = run(f'openssl x509 -noout -subject -dates -in {cert_path}', capture=True)
print(info.stdout.strip())


# ── 3. Build fullchain with Cloudflare Origin RSA CA ─────────────────────────
step('3/7  Building fullchain with Cloudflare Origin CA')

CF_RSA_CA_URL = 'https://developers.cloudflare.com/ssl/static/origin_ca_rsa_root.pem'
CF_ECC_CA_URL = 'https://developers.cloudflare.com/ssl/static/origin_ca_ecc_root.pem'

ca_pem = None
for url in [CF_RSA_CA_URL, CF_ECC_CA_URL]:
    try:
        ca_pem = urllib.request.urlopen(url, timeout=15).read().decode()
        print(f'Downloaded CA from {url}')
        break
    except Exception as e:
        print(f'Could not download {url}: {e}')

if ca_pem:
    with open(fc_path, 'w') as f:
        f.write(CERT + ca_pem)
    os.chmod(fc_path, 0o644)
    print(f'Fullchain written: {len(CERT) + len(ca_pem)} bytes → {fc_path}')
else:
    # Fallback: use cert alone (Full mode works, Full strict may not)
    with open(fc_path, 'w') as f:
        f.write(CERT)
    os.chmod(fc_path, 0o644)
    print('WARNING: Could not download CA — using cert only (try Full mode in Cloudflare)')


# ── 4. Write Nginx config ─────────────────────────────────────────────────────
step('4/7  Writing Nginx configuration')

with open(NGINX_AVAILABLE, 'w') as f:
    f.write(NGINX_CONF)

# Enable site, remove default
if not os.path.islink(NGINX_ENABLED):
    os.symlink(NGINX_AVAILABLE, NGINX_ENABLED)
default = '/etc/nginx/sites-enabled/default'
if os.path.exists(default):
    os.remove(default)

# Open firewall ports
run('ufw allow 80/tcp 2>/dev/null || true', check=False)
run('ufw allow 443/tcp 2>/dev/null || true', check=False)
run('ufw --force enable 2>/dev/null || true', check=False)

# Test nginx
r = run('nginx -t 2>&1', capture=True)
print(r.stdout + r.stderr)
if 'successful' not in (r.stdout + r.stderr):
    print('ERROR: Nginx config test failed!')
    sys.exit(1)

run('systemctl reload nginx')
print('✅ Nginx reloaded')


# ── 5. Update .env ────────────────────────────────────────────────────────────
step('5/7  Updating .env')

if os.path.exists(ENV_FILE):
    with open(ENV_FILE) as f:
        env_content = f.read()

    updates = {
        'ALLOWED_HOSTS':       'duno360.com,www.duno360.com,159.203.186.103,localhost,127.0.0.1',
        'CSRF_TRUSTED_ORIGINS': 'https://duno360.com,https://www.duno360.com',
        'FORCE_HTTPS':          'True',
    }

    for key, value in updates.items():
        pattern = rf'^{re.escape(key)}=.*$'
        new_line = f'{key}={value}'
        if re.search(pattern, env_content, re.MULTILINE):
            env_content = re.sub(pattern, new_line, env_content, flags=re.MULTILINE)
        else:
            env_content = env_content.rstrip('\n') + '\n' + new_line + '\n'

    with open(ENV_FILE, 'w') as f:
        f.write(env_content)

    for key in updates:
        r = run(f'grep "^{key}=" {ENV_FILE}', capture=True, check=False)
        print(r.stdout.strip())
else:
    print(f'WARNING: {ENV_FILE} not found — skipping env update')


# ── 6. Run Django migrations ──────────────────────────────────────────────────
step('6/7  Running Django migrations')

env = os.environ.copy()
env['DJANGO_SETTINGS_MODULE'] = 'book_Project.settings'

# Load .env into environment
if os.path.exists(ENV_FILE):
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                k, _, v = line.partition('=')
                env.setdefault(k.strip(), v.strip())

r = run(
    f'{VENV} manage.py migrate --run-syncdb 2>&1',
    capture=True, cwd=APP_DIR, env=env
)
output = r.stdout or r.stderr
# Show last 20 lines
lines = output.strip().splitlines()
for line in lines[-20:]:
    print(line)

# Collectstatic
r2 = run(
    f'{VENV} manage.py collectstatic --noinput 2>&1',
    capture=True, cwd=APP_DIR, env=env
)
lines2 = (r2.stdout or '').strip().splitlines()
for line in lines2[-5:]:
    print(line)


# ── 7. Restart app service ────────────────────────────────────────────────────
step('7/7  Restarting duno360 service')

run('systemctl restart duno360')
time.sleep(3)
r = run('systemctl is-active duno360', capture=True, check=False)
status = r.stdout.strip()
print(f'Service status: {status}')

if status != 'active':
    print('ERROR: Service did not start! Last logs:')
    run('journalctl -u duno360 -n 30 --no-pager', check=False)
    sys.exit(1)

# Quick local HTTP check
r = run('curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/manager/public/', capture=True, check=False)
print(f'Local HTTP check: {r.stdout.strip()}')


# ── Summary ───────────────────────────────────────────────────────────────────
print(f"""
{'='*60}
✅ HTTPS SETUP COMPLETE

SSL cert: {fc_path}
Nginx:    Full HTTPS on port 443

CLOUDFLARE - Required settings:
  DNS:     A  duno360.com     → 159.203.186.103  (Proxied ON)
  DNS:     A  www.duno360.com → 159.203.186.103  (Proxied ON)
  SSL/TLS: Full (strict)

Site: https://duno360.com/manager/public/
{'='*60}
""")
