# Generated by Django 5.2 on 2026-03-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(blank=True, default='', max_length=200, verbose_name='主题')),
                ('message', models.TextField(verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('email_sent', models.BooleanField(default=False, verbose_name='邮件已发送')),
            ],
            options={
                'verbose_name': '联系留言',
                'verbose_name_plural': '联系留言',
                'db_table': 'contact_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
