# Generated by Django 5.2 on 2026-03-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址')),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=200, verbose_name='IMAP服务器')),
                ('imap_port', models.IntegerField(default=993, verbose_name='IMAP端口')),
                ('imap_use_ssl', models.BooleanField(default=True, verbose_name='IMAP SSL')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='SMTP服务器')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP端口')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='SMTP TLS')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(max_length=500, verbose_name='密码/应用密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认账户')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='最后同步')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮箱账户',
                'verbose_name_plural': '邮箱账户',
                'db_table': 'email_account',
            },
        ),
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('color', models.CharField(default='#667eea', max_length=7, verbose_name='颜色')),
                ('icon', models.CharField(default='fa-tag', max_length=50, verbose_name='图标')),
            ],
            options={
                'verbose_name': '邮件标签',
                'verbose_name_plural': '邮件标签',
                'db_table': 'email_label',
            },
        ),
        migrations.CreateModel(
            name='EmailAutoRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('match_field', models.CharField(choices=[('from', '发件人'), ('to', '收件人'), ('subject', '主题'), ('body', '正文'), ('any', '任意字段')], default='any', max_length=20, verbose_name='匹配字段')),
                ('match_pattern', models.CharField(max_length=500, verbose_name='匹配关键词')),
                ('action', models.CharField(choices=[('label', '添加标签'), ('star', '添加星标'), ('archive', '归档'), ('delete', '删除'), ('auto_reply', '自动回复'), ('forward', '转发'), ('mark_read', '标记已读')], default='label', max_length=20, verbose_name='执行操作')),
                ('action_forward_to', models.EmailField(blank=True, default='', max_length=254, verbose_name='转发地址')),
                ('auto_reply_subject', models.CharField(blank=True, default='', max_length=500, verbose_name='自动回复主题')),
                ('auto_reply_body', models.TextField(blank=True, default='', verbose_name='自动回复内容')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('apply_to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.emailaccount', verbose_name='应用到账户')),
                ('action_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.emaillabel', verbose_name='目标标签')),
            ],
            options={
                'verbose_name': '邮件规则',
                'verbose_name_plural': '邮件规则',
                'db_table': 'email_auto_rule',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_uid', models.CharField(blank=True, default='', max_length=500, verbose_name='邮件UID')),
                ('sender_name', models.CharField(blank=True, default='', max_length=300, verbose_name='发件人名称')),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='发件人邮箱')),
                ('recipients', models.TextField(default='', verbose_name='收件人')),
                ('cc', models.TextField(blank=True, default='', verbose_name='抄送')),
                ('bcc', models.TextField(blank=True, default='', verbose_name='密送')),
                ('subject', models.CharField(default='(无主题)', max_length=1000, verbose_name='主题')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='纯文本内容')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='HTML内容')),
                ('folder', models.CharField(choices=[('inbox', '收件箱'), ('sent', '已发送'), ('draft', '草稿'), ('trash', '已删除'), ('archive', '归档')], default='inbox', max_length=20, verbose_name='文件夹')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('is_starred', models.BooleanField(default=False, verbose_name='星标')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=500, verbose_name='回复ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='manager.emailaccount', verbose_name='邮箱账户')),
                ('labels', models.ManyToManyField(blank=True, related_name='emails', to='manager.emaillabel', verbose_name='标签')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
                'db_table': 'email_message',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, verbose_name='文件名')),
                ('content_type', models.CharField(blank=True, default='', max_length=200, verbose_name='文件类型')),
                ('file', models.FileField(upload_to='email_attachments/%Y/%m/', verbose_name='文件')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manager.emailmessage', verbose_name='邮件')),
            ],
            options={
                'verbose_name': '邮件附件',
                'verbose_name_plural': '邮件附件',
                'db_table': 'email_attachment',
            },
        ),
    ]
