# Generated by Django 5.2 on 2026-03-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_emailaccount_emaillabel_emailautorule_emailmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='contact_messages', to='manager.emaillabel', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied',
            field=models.BooleanField(default=False, verbose_name='已回复'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回复时间'),
        ),
    ]
