# Generated by Django 5.2 on 2026-03-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_contactmessage_labels_contactmessage_replied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/', verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点用户',
                'verbose_name_plural': '站点用户',
                'db_table': 'site_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司/店铺名称')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('description', models.TextField(blank=True, default='', verbose_name='店铺描述')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/', verbose_name='Logo')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('suspended', '已暂停')], default='pending', max_length=20, verbose_name='状态')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='佣金比例(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='manager.siteuser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '卖家',
                'verbose_name_plural': '卖家',
                'db_table': 'vendor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='卖家定价')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.book', verbose_name='图书')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.vendor', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '卖家图书',
                'verbose_name_plural': '卖家图书',
                'db_table': 'vendor_book',
                'unique_together': {('vendor', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'wishlist',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
