# Generated by Django 5.2 on 2026-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_siteuser_vendor_vendorbook_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('pin_code', models.CharField(max_length=6, verbose_name='验证码')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('password', models.CharField(max_length=128, verbose_name='密码(已加密)')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证',
                'db_table': 'email_verification',
                'ordering': ['-created_at'],
            },
        ),
    ]
