# Generated by Django 5.2 on 2026-03-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', '新订单'), ('new_user', '新用户注册'), ('abandoned_cart', '待下单提醒'), ('incomplete_registration', '未完成注册'), ('order_paid', '订单已付款'), ('vendor_registered', '新卖家注册'), ('low_stock', '库存不足')], max_length=30, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('icon', models.CharField(default='fas fa-bell', max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#667eea', max_length=20, verbose_name='颜色')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '管理员通知',
                'verbose_name_plural': '管理员通知',
                'db_table': 'admin_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
