# Generated by Django 5.2 on 2026-03-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='verification_type',
            field=models.CharField(choices=[('user', '用户注册'), ('vendor', '卖家注册')], default='user', max_length=10, verbose_name='验证类型'),
        ),
    ]
