# Generated by Django 5.2 on 2026-03-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_emailverification_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Config', max_length=100, verbose_name='配置名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('qwen', 'Alibaba (Qwen/通义千问)'), ('deepseek', 'DeepSeek'), ('custom', 'Custom / Local')], default='openai', max_length=20, verbose_name='AI 提供商')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API Key')),
                ('model_name', models.CharField(blank=True, default='', help_text='e.g. gpt-4o, claude-3-5-sonnet-20241022, gemini-1.5-pro, qwen-plus', max_length=100, verbose_name='模型名称')),
                ('api_endpoint', models.CharField(blank=True, default='', help_text='Leave blank to use provider default', max_length=500, verbose_name='自定义 API 地址')),
                ('system_prompt', models.TextField(default='你是一个友好、专业的图书管理系统助手。你帮助用户了解图书、作者、出版社信息，并回答关于购书、订单等问题。请用简洁、友好的语言回答。', verbose_name='系统提示词 (System Prompt)')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='最大 Token 数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度 (0.0 - 2.0)')),
                ('widget_title', models.CharField(default='AI 助手', max_length=100, verbose_name='聊天窗口标题')),
                ('widget_subtitle', models.CharField(default='有什么可以帮助你的？', max_length=200, verbose_name='副标题')),
                ('welcome_message', models.TextField(default='你好！我是 AI 助手，有什么可以帮助你的吗？', verbose_name='欢迎消息')),
                ('show_on_public', models.BooleanField(default=True, verbose_name='在前端显示')),
                ('show_on_admin', models.BooleanField(default=True, verbose_name='在管理后台显示')),
                ('max_messages_per_session', models.IntegerField(default=50, verbose_name='每会话最大消息数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '聊天机器人配置',
                'verbose_name_plural': '聊天机器人配置',
                'db_table': 'chatbot_config',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='Session Key')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='最近活跃')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数')),
                ('is_closed', models.BooleanField(default=False)),
                ('context', models.TextField(blank=True, default='', verbose_name='上下文摘要')),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='manager.chatbotconfig', verbose_name='配置')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'chat_session',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Token 用量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='manager.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
