# Generated by Django 5.2 on 2026-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_chatbotconfig_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True, default='', verbose_name='管理员回复'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='会话标识'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('qwen', 'Alibaba (Qwen/通义千问)'), ('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter'), ('custom', 'Custom / Local')], default='openai', max_length=20, verbose_name='AI 提供商'),
        ),
    ]
