# Generated by Django 5.2 on 2026-03-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_contactmessage_admin_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='is_dismissed',
            field=models.BooleanField(default=False, verbose_name='已清除'),
        ),
    ]
