# Generated by Django 5.2 on 2026-03-31 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_adminnotification_is_dismissed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item_type',
            field=models.CharField(choices=[('book', '图书'), ('product', '商品'), ('course', '课程'), ('supermarket', '超市商品')], default='book', max_length=20, verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', '新订单'), ('new_user', '新用户注册'), ('abandoned_cart', '待下单提醒'), ('incomplete_registration', '未完成注册'), ('order_paid', '订单已付款'), ('vendor_registered', '新卖家注册'), ('low_stock', '库存不足'), ('contact_message', '联系消息'), ('cs_chat', '客服聊天')], max_length=30, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.book', verbose_name='图书'),
        ),
    ]
