# Generated by Django 4.2.29 on 2026-03-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_wishlist_unique_together_wishlist_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mtn_money', 'MTN Money'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('wechat_pay', '微信支付'), ('alipay', '支付宝'), ('paypal', 'PayPal'), ('credit_card', 'Visa / Mastercard'), ('bank_transfer', '银行转账')], max_length=20, verbose_name='支付方式'),
        ),
        migrations.CreateModel(
            name='VendorMarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', '商品'), ('course', '课程')], max_length=20, verbose_name='商品类型')),
                ('item_id', models.PositiveIntegerField(verbose_name='商品ID')),
                ('vendor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='卖家定价')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items', to='manager.vendor', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '卖家市场商品',
                'verbose_name_plural': '卖家市场商品',
                'db_table': 'vendor_marketplace_item',
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'item_type', 'item_id')},
            },
        ),
    ]
