# Generated by Django 4.2.29 on 2026-03-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_order_payment_method_vendormarketplaceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorMarketplaceItem',
        ),
    ]
