# Generated by Django 4.2.29 on 2026-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_delete_vendormarketplaceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotconfig',
            name='system_prompt',
            field=models.TextField(default='你是DUNO 360平台的友好、专业助手。你帮助用户了解图书、作者、出版社、在线课程、市场商品和生鲜超市信息，并回答关于购物、订单等问题。请用简洁、友好的语言回答。', verbose_name='系统提示词 (System Prompt)'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verification_type',
            field=models.CharField(choices=[('user', '用户注册'), ('vendor', '卖家注册'), ('password_reset', '密码重置')], default='user', max_length=20, verbose_name='验证类型'),
        ),
    ]
