# Generated by Django 5.2 on 2026-04-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_chatbotconfig_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='管理员权限'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, verbose_name='会话密钥'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='客户邮箱'),
        ),
    ]
