# Generated by Django 5.2 on 2026-04-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_manager_is_admin_alter_book_name_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name_fr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name_zh_hans',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_en',
            field=models.TextField(blank=True, help_text='图书详细描述信息', null=True, verbose_name='图书描述'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_fr',
            field=models.TextField(blank=True, help_text='图书详细描述信息', null=True, verbose_name='图书描述'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_zh_hans',
            field=models.TextField(blank=True, help_text='图书详细描述信息', null=True, verbose_name='图书描述'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_address_en',
            field=models.CharField(max_length=32, null=True, verbose_name='出版社地址'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_address_fr',
            field=models.CharField(max_length=32, null=True, verbose_name='出版社地址'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_address_zh_hans',
            field=models.CharField(max_length=32, null=True, verbose_name='出版社地址'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='出版社名称'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_name_fr',
            field=models.CharField(max_length=32, null=True, verbose_name='出版社名称'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_name_zh_hans',
            field=models.CharField(max_length=32, null=True, verbose_name='出版社名称'),
        ),
    ]
