# Generated by Django 6.0.4 on 2026-04-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_author_name_en_author_name_fr_author_name_zh_hans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_zh_hans',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_fr',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='标题'),
        ),
    ]
