# Generated by Django 6.0.4 on 2026-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_blogpost_content_en_blogpost_content_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='publisher_address',
            field=models.CharField(max_length=128, verbose_name='出版社地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_address_en',
            field=models.CharField(max_length=128, null=True, verbose_name='出版社地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_address_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='出版社地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_address_zh_hans',
            field=models.CharField(max_length=128, null=True, verbose_name='出版社地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name',
            field=models.CharField(max_length=128, verbose_name='出版社名称'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='出版社名称'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='出版社名称'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name_zh_hans',
            field=models.CharField(max_length=128, null=True, verbose_name='出版社名称'),
        ),
    ]
