# Generated by Django 6.0.4 on 2026-04-30 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_publisher_fields_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='积分余额')),
                ('lifetime_points', models.PositiveIntegerField(default=0, verbose_name='累计积分')),
                ('tier', models.CharField(choices=[('bronze', '铜牌'), ('silver', '银牌'), ('gold', '金牌'), ('platinum', '白金')], default='bronze', max_length=20, verbose_name='会员等级')),
                ('last_spin', models.DateField(blank=True, null=True, verbose_name='上次转盘日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分账户',
                'verbose_name_plural': '积分账户',
                'db_table': 'loyalty_points',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='积分变动(正=增加,负=扣除)')),
                ('reason', models.CharField(choices=[('purchase', '购买'), ('review', '评价'), ('daily_spin', '每日转盘'), ('referral', '推荐好友'), ('redeem', '积分兑换'), ('admin', '管理员调整')], max_length=20, verbose_name='原因')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'db_table': 'point_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
