# Generated by Django 6.0.4 on 2026-04-30 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_loyaltypoints_pointtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowedShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='manager.publisher', verbose_name='出版商')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_shops', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注的店铺',
                'verbose_name_plural': '关注的店铺',
                'db_table': 'user_followed_shop',
                'ordering': ['-followed_at'],
                'unique_together': {('user', 'publisher')},
            },
        ),
    ]
