# Generated by Django 6.0.4 on 2026-04-30 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_userfollowedshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='英文名称')),
                ('name_fr', models.CharField(blank=True, default='', max_length=100, verbose_name='法文名称')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.CharField(default='fas fa-book', max_length=50, verbose_name='图标CSS类')),
                ('color', models.CharField(default='#667eea', max_length=7, verbose_name='颜色(hex)')),
                ('display_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='manager.bookcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'db_table': 'book_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='manager.bookcategory', verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('buyer_seller', '买家-卖家'), ('support', '用户-客服'), ('vendor_support', '卖家-客服')], default='support', max_length=20, verbose_name='会话类型')),
                ('subject', models.CharField(blank=True, default='', max_length=200, verbose_name='主题')),
                ('ref_item_type', models.CharField(blank=True, default='', max_length=20, verbose_name='商品类型')),
                ('ref_item_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='商品ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='已关闭')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to='manager.siteuser', verbose_name='买家')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_conversations', to='manager.vendor', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'db_table': 'conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('buyer', '买家'), ('vendor', '卖家'), ('admin', '管理员')], max_length=10, verbose_name='发送方类型')),
                ('sender_name', models.CharField(blank=True, default='', max_length=100, verbose_name='发送方名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/%Y/%m/', verbose_name='附件')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='manager.conversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'direct_message',
                'ordering': ['created_at'],
            },
        ),
    ]
