# Generated by Django 6.0.4 on 2026-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_userfollowedvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, default='', verbose_name='收货地址'),
        ),
    ]
