# Generated by Django 6.0.4 on 2026-05-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_order_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', '新订单'), ('new_message', '新消息'), ('order_paid', '订单已付款'), ('order_shipped', '订单已发货'), ('low_stock', '库存不足'), ('new_review', '新评价'), ('system', '系统通知')], max_length=30, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('icon', models.CharField(default='fas fa-bell', max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#10b981', max_length=20, verbose_name='颜色')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='manager.vendor', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '卖家通知',
                'verbose_name_plural': '卖家通知',
                'db_table': 'vendor_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
