# Generated by Django 5.2 on 2026-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_vendor_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='KkiapayCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (Français)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('iso_code', models.CharField(max_length=2, unique=True, verbose_name='Code ISO 3166-1 alpha-2')),
                ('phone_code', models.CharField(max_length=10, verbose_name='Indicatif téléphonique')),
                ('currency_code', models.CharField(default='XOF', max_length=3, verbose_name='Code devise ISO 4217')),
                ('currency_name_fr', models.CharField(max_length=100, verbose_name='Nom devise')),
                ('mobile_operators', models.JSONField(default=list, verbose_name='Opérateurs mobiles')),
                ('flag_emoji', models.CharField(blank=True, default='', max_length=10, verbose_name='Drapeau emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre affichage')),
            ],
            options={
                'verbose_name': 'Pays KKiaPay',
                'verbose_name_plural': 'Pays KKiaPay',
                'db_table': 'kkiapay_country',
                'ordering': ['display_order', 'name_fr'],
            },
        ),
    ]
