# Generated by Django 5.2 on 2026-05-29 20:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_add_kkiapay_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='充值单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额')),
                ('payment_method', models.CharField(max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100, verbose_name='外部交易号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_orders', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值订单',
                'verbose_name_plural': '充值订单',
                'db_table': 'topup_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='余额')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='累计充值')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='累计消费')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户钱包',
                'verbose_name_plural': '用户钱包',
                'db_table': 'user_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额(负=支出)')),
                ('txn_type', models.CharField(choices=[('credit', '充值'), ('debit', '消费'), ('refund', '退款'), ('bonus', '平台赠送')], max_length=20, verbose_name='类型')),
                ('source', models.CharField(choices=[('deposit', '用户充值'), ('order_payment', '订单支付'), ('order_refund', '订单退款'), ('loyalty_convert', '积分兑换'), ('admin_adjust', '管理员调整'), ('promo_bonus', '活动奖励')], max_length=20, verbose_name='来源')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('source_id', models.CharField(blank=True, default='', max_length=50, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '钱包流水',
                'verbose_name_plural': '钱包流水',
                'db_table': 'wallet_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
