# Generated by Django 5.2 on 2026-06-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_emailverification_phone_verified'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformescrowtransaction',
            new_name='platform_es_vendor__95faaa_idx',
            old_name='platform_es_vendor__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='platformescrowtransaction',
            new_name='platform_es_order_n_974cd9_idx',
            old_name='platform_es_order_n_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='platformescrowtransaction',
            new_name='platform_es_buyer_e_dee389_idx',
            old_name='platform_es_buyer_e_g7h8i9_idx',
        ),
        migrations.AlterField(
            model_name='platformescrowtransaction',
            name='item_type',
            field=models.CharField(choices=[('book', '图书'), ('product', '商品'), ('course', '课程'), ('supermarket', '超市')], max_length=20, verbose_name='Type article'),
        ),
        migrations.AlterField(
            model_name='platformescrowtransaction',
            name='order_source',
            field=models.CharField(choices=[('book', '图书订单'), ('marketplace', '商城订单')], max_length=20, verbose_name='Source commande'),
        ),
        migrations.AlterField(
            model_name='platformescrowtransaction',
            name='status',
            field=models.CharField(choices=[('held', '托管中'), ('releasable', '可结算'), ('released', '已到账'), ('refunded', '已退款'), ('cancelled', '已取消')], default='held', max_length=20, verbose_name='Statut escrow'),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', '新订单'), ('new_message', '新消息'), ('order_paid', '订单已付款'), ('abandoned_checkout', '未付款订单'), ('new_follower', '新关注'), ('wishlist_add', '收藏商品'), ('order_shipped', '订单已发货'), ('low_stock', '库存不足'), ('new_review', '新评价'), ('system', '系统通知')], max_length=30, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='vendorwallettransaction',
            name='source',
            field=models.CharField(choices=[('escrow_release', '托管释放'), ('admin_adjust', '管理员调整'), ('payout_request', '提现申请')], max_length=30, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='vendorwallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('credit', '入账'), ('debit', '出账'), ('payout', '提现')], max_length=20, verbose_name='Type'),
        ),
    ]
