# Generated by Django 5.2 on 2026-06-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_order_city'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendor_is_official_idx',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='city',
            field=models.CharField(default='Brazzaville', max_length=64, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='location',
            field=models.CharField(choices=[('Brazzaville', 'Brazzaville'), ('Pointe-Noire', 'Pointe-Noire'), ('Bouenza', 'Bouenza'), ('Niari', 'Niari'), ('Pool', 'Pool'), ('Plateaux', 'Plateaux'), ('Cuvette', 'Cuvette'), ('Cuvette-Ouest', 'Cuvette-Ouest'), ('Sangha', 'Sangha'), ('Likouala', 'Likouala'), ('Kouilou', 'Kouilou'), ('Lékoumou', 'Lékoumou'), ('Congo-Oubangui', 'Congo-Oubangui'), ('Nkéni-Alima', 'Nkéni-Alima'), ('Djoué-Léfini', 'Djoué-Léfini')], default='Brazzaville', max_length=64, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_official',
            field=models.BooleanField(db_index=True, default=False, verbose_name='官方直营店'),
        ),
    ]
