# Generated by Django 5.2 on 2026-06-12 22:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0047_remove_vendorbook_vendor_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='项目标题')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='项目摘要')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('beneficiary_type', models.CharField(choices=[('orphans', '孤儿支持'), ('disadvantaged', '困难群体支持'), ('education', '教育支持'), ('health', '医疗支持'), ('community', '社区援助')], default='disadvantaged', max_length=30, verbose_name='受益对象')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('goal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='目标金额')),
                ('raised_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='已筹金额')),
                ('sort_priority', models.PositiveIntegerField(default=0, verbose_name='排序优先级')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='donation_campaigns/', verbose_name='封面图')),
                ('is_featured', models.BooleanField(default=False, verbose_name='重点项目')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公益捐赠项目',
                'verbose_name_plural': '公益捐赠项目',
                'db_table': 'donation_campaign',
                'ordering': ['-is_featured', '-sort_priority', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verification_type',
            field=models.CharField(choices=[('user', '用户注册'), ('vendor', '卖家注册'), ('password_reset', '密码重置'), ('vendor_activation_payment', '卖家激活支付')], default='user', max_length=25, verbose_name='验证类型'),
        ),
        migrations.CreateModel(
            name='DonationContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, default='', max_length=120, verbose_name='捐赠人姓名')),
                ('donor_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='捐赠人电话')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='捐赠金额')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='币种')),
                ('payment_provider', models.CharField(default='pawapay', max_length=20, verbose_name='支付渠道')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='支付状态')),
                ('external_reference', models.CharField(blank=True, default='', max_length=120, verbose_name='外部参考号')),
                ('public_message', models.CharField(blank=True, default='', max_length=255, verbose_name='公开留言')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名捐赠')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='manager.donationcampaign', verbose_name='捐赠项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='manager.siteuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '公益捐赠记录',
                'verbose_name_plural': '公益捐赠记录',
                'db_table': 'donation_contribution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerActivationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40, unique=True, verbose_name='激活单号')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, verbose_name='支付金额')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='币种')),
                ('provider', models.CharField(choices=[('pawapay', 'pawaPay')], default='pawapay', max_length=20, verbose_name='支付通道')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('processing', '支付处理中'), ('paid', '已支付'), ('failed', '支付失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='支付状态')),
                ('payer_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='付款手机号')),
                ('payer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='付款人姓名')),
                ('external_reference', models.CharField(blank=True, default='', max_length=120, verbose_name='外部参考号')),
                ('external_status', models.CharField(blank=True, default='', max_length=60, verbose_name='外部状态')),
                ('provider_message', models.CharField(blank=True, default='', max_length=255, verbose_name='支付反馈')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_activation_payments', to='manager.siteuser', verbose_name='用户')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_payments', to='manager.vendor', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '卖家激活支付',
                'verbose_name_plural': '卖家激活支付',
                'db_table': 'seller_activation_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
