# Generated by Django 5.2.15 on 2026-07-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_donationcampaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='config',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatbotConfig',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
