# Generated by Django 6.0.4 on 2026-07-03 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_conversation_conv_updated_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_hidden',
            field=models.BooleanField(default=False, verbose_name='买家已删除（仅本地隐藏）'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], default='', max_length=10, verbose_name='附件类型'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='deleted_for_buyer',
            field=models.BooleanField(default=False, verbose_name='买家已删除（仅本地隐藏）'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='is_recalled',
            field=models.BooleanField(default=False, verbose_name='已撤回（双方不可见）'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='manager.directmessage', verbose_name='引用消息'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.CreateModel(
            name='VendorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_vendors', to='manager.siteuser', verbose_name='买家')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_buyers', to='manager.vendor', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '卖家黑名单',
                'verbose_name_plural': '卖家黑名单',
                'db_table': 'vendor_block',
                'unique_together': {('buyer', 'vendor')},
            },
        ),
    ]
