# Generated by Django 6.0.4 on 2026-07-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_conversation_buyer_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='vendor_hidden',
            field=models.BooleanField(default=False, verbose_name='卖家已删除（仅本地隐藏）'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='deleted_for_vendor',
            field=models.BooleanField(default=False, verbose_name='卖家已删除（仅本地隐藏）'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='', max_length=10, verbose_name='附件类型'),
        ),
    ]
