# Generated by Django 6.0.4 on 2026-07-05 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_conversation_vendor_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='away_reply_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='自动离开回复已发送时间'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='is_auto_reply',
            field=models.BooleanField(default=False, verbose_name='自动回复'),
        ),
        migrations.CreateModel(
            name='AutoReplyKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255, verbose_name='关键词（英文逗号分隔）')),
                ('reply_message', models.TextField(verbose_name='自动回复内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_keywords', to='manager.vendor', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '关键词自动回复',
                'verbose_name_plural': '关键词自动回复',
                'db_table': 'auto_reply_keyword',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoReplySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_enabled', models.BooleanField(default=False, verbose_name='启用欢迎语')),
                ('welcome_message', models.TextField(blank=True, default='', verbose_name='欢迎语内容')),
                ('away_enabled', models.BooleanField(default=False, verbose_name='启用离开自动回复')),
                ('away_message', models.TextField(blank=True, default='', verbose_name='离开自动回复内容')),
                ('away_delay_minutes', models.PositiveIntegerField(default=5, verbose_name='离开回复延迟（分钟）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_settings', to='manager.vendor', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '自动回复设置',
                'verbose_name_plural': '自动回复设置',
                'db_table': 'auto_reply_settings',
            },
        ),
    ]
