# Generated by Django 6.0.4 on 2026-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0053_conversation_away_reply_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreplysettings',
            name='away_delay_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='离开回复延迟（分钟）'),
        ),
        migrations.AlterField(
            model_name='autoreplysettings',
            name='away_message',
            field=models.TextField(blank=True, default='您好，我们暂时不在线，通常会在10分钟内回复您。感谢您的耐心等待，我们会尽快与您联系！', verbose_name='离开自动回复内容'),
        ),
        migrations.AlterField(
            model_name='autoreplysettings',
            name='welcome_message',
            field=models.TextField(blank=True, default='您好，欢迎光临 DUNO 360！感谢您的咨询，我们已收到您的消息，会尽快为您处理，请稍候片刻。', verbose_name='欢迎语内容'),
        ),
    ]
