# Generated by Django 6.0.4 on 2026-07-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_alter_autoreplysettings_away_delay_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreplysettings',
            name='away_enabled',
            field=models.BooleanField(default=True, verbose_name='启用离开自动回复'),
        ),
        migrations.AlterField(
            model_name='autoreplysettings',
            name='away_message',
            field=models.TextField(blank=True, default="Bonjour, nous ne sommes pas disponibles pour le moment et répondons généralement sous 10 minutes. Merci de votre patience, nous revenons vers vous très vite !\n\nHello, we're currently unavailable and usually reply within 10 minutes. Thank you for your patience — we'll get back to you shortly!", verbose_name='离开自动回复内容'),
        ),
        migrations.AlterField(
            model_name='autoreplysettings',
            name='welcome_enabled',
            field=models.BooleanField(default=True, verbose_name='启用欢迎语'),
        ),
        migrations.AlterField(
            model_name='autoreplysettings',
            name='welcome_message',
            field=models.TextField(blank=True, default="Bonjour et bienvenue chez DUNO 360 ! Merci de nous avoir contactés, nous avons bien reçu votre message et nous vous répondrons très rapidement.\n\nHello and welcome to DUNO 360! Thank you for contacting us — we've received your message and will get back to you very soon.", verbose_name='欢迎语内容'),
        ),
    ]
