# Generated by Django 6.0.4 on 2026-07-12 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0056_backfill_auto_reply_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='city',
            field=models.CharField(default='Makélékélé', max_length=64, verbose_name='Ville'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_source', models.CharField(choices=[('book', '图书订单'), ('marketplace', '商城订单')], max_length=20, verbose_name='Source commande')),
                ('order_id', models.PositiveIntegerField(db_index=True, verbose_name='ID commande')),
                ('order_number', models.CharField(db_index=True, max_length=32, verbose_name='N° commande')),
                ('fulfillment_status', models.CharField(choices=[('awaiting_acceptance', "En attente d'acceptation"), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('packing', 'En préparation'), ('shipped', 'Expédiée'), ('in_transit', 'En transit'), ('out_for_delivery', 'En livraison'), ('delivered', 'Livrée'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('return_requested', 'Retour demandé'), ('return_approved', 'Retour approuvé'), ('return_rejected', 'Retour refusé'), ('returned', 'Retournée')], db_index=True, default='awaiting_acceptance', max_length=20, verbose_name='Statut logistique')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100, verbose_name='N° de suivi')),
                ('carrier', models.CharField(blank=True, default='', max_length=100, verbose_name='Transporteur')),
                ('accept_by', models.DateTimeField(blank=True, null=True, verbose_name='Accepter avant (SLA)')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Acceptée le')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Refusée le')),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif de refus')),
                ('packed_at', models.DateTimeField(blank=True, null=True, verbose_name='Préparée le')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Expédiée le')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='Livraison estimée')),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True, verbose_name='En livraison depuis')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livrée le')),
                ('delivered_confirmed_by', models.CharField(blank=True, choices=[('buyer', 'Acheteur'), ('auto_timeout', 'Automatique'), ('admin', 'Admin')], default='', max_length=20, verbose_name='Confirmée par')),
                ('auto_confirm_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmation automatique prévue')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le (escrow libéré)')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='manager.vendor', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Expédition',
                'verbose_name_plural': 'Expéditions',
                'db_table': 'shipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom acheteur')),
                ('buyer_email', models.EmailField(db_index=True, max_length=254, verbose_name='Email acheteur')),
                ('reason', models.CharField(choices=[('not_received', 'Colis non reçu'), ('damaged', 'Article endommagé'), ('wrong_item', 'Mauvais article reçu'), ('not_as_described', 'Non conforme à la description'), ('other', 'Autre')], max_length=30, verbose_name='Motif')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Photos justificatives')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('resolved', 'Résolue')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='Note de résolution')),
                ('resolved_by', models.CharField(blank=True, choices=[('vendor', 'Vendeur'), ('admin', 'Admin')], default='', max_length=20, verbose_name='Résolu par')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='manager.shipment', verbose_name='Expédition')),
            ],
            options={
                'verbose_name': 'Demande de retour',
                'verbose_name_plural': 'Demandes de retour',
                'db_table': 'order_return_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_items', to='manager.shipment', verbose_name='Expédition'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order_source', 'order_id'], name='shipment_order_s_38185a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['vendor', 'fulfillment_status'], name='shipment_vendor__df9c83_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order_number'], name='shipment_order_n_38df05_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['fulfillment_status', 'auto_confirm_at'], name='shipment_fulfill_ddc869_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['fulfillment_status', 'accept_by'], name='shipment_fulfill_7ec22f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturnrequest',
            index=models.Index(fields=['status'], name='order_retur_status_9f9f63_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturnrequest',
            index=models.Index(fields=['buyer_email'], name='order_retur_buyer_e_d81d7e_idx'),
        ),
    ]
