# Generated by Django 6.0.4 on 2026-07-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_alter_emailverification_city_shipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_source', models.CharField(choices=[('book', '图书订单'), ('marketplace', '商城订单')], max_length=20, verbose_name='Source commande')),
                ('order_id', models.PositiveIntegerField(db_index=True, verbose_name='ID commande')),
                ('order_number', models.CharField(db_index=True, max_length=32, verbose_name='N° commande')),
                ('provider', models.CharField(choices=[('pawapay', 'pawaPay')], default='pawapay', max_length=20, verbose_name='Prestataire')),
                ('provider_refund_id', models.CharField(max_length=64, unique=True, verbose_name='ID remboursement externe')),
                ('provider_deposit_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID dépôt externe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('failed', 'Échoué')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('provider_message', models.CharField(blank=True, default='', max_length=255, verbose_name='Message prestataire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Initié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='manager.shipment', verbose_name='Expédition (vide = remboursement commande entière)')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'db_table': 'order_refund',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='order_refun_status_58f35c_idx'), models.Index(fields=['order_number'], name='order_refun_order_n_a5ebcb_idx')],
            },
        ),
    ]
