# Generated by Django 6.0.4 on 2026-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0058_orderrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='review_request_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rappel avis envoyé le'),
        ),
    ]
