# Generated by Django 6.0.4 on 2026-07-12 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0059_shipment_review_request_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='爱心捐赠金额'),
        ),
    ]
