# Generated by Django 6.0.4 on 2026-07-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0060_order_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', '新订单'), ('new_user', '新用户注册'), ('abandoned_cart', '待下单提醒'), ('incomplete_registration', '未完成注册'), ('order_paid', '订单已付款'), ('vendor_registered', '新卖家注册'), ('low_stock', '库存不足'), ('contact_message', '联系消息'), ('cs_chat', '客服聊天'), ('donation_received', '收到爱心捐赠')], max_length=30, verbose_name='类型'),
        ),
    ]
