# Generated by Django 6.0.4 on 2026-07-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0062_book_delivery_days_max_book_delivery_days_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_applied',
            field=models.BooleanField(default=False, help_text="Set once stock/sales counters have been deducted for this order's items — happens exactly once, when payment is first confirmed, never at order creation. Guards against double-deduction.", verbose_name='库存已扣减'),
        ),
    ]
