# Generated by Django 6.0.4 on 2026-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0063_order_inventory_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='country',
            field=models.CharField(choices=[('Congo', 'Congo'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Cameroon', 'Cameroon'), ('Gabon', 'Gabon'), ('Angola', 'Angola'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Equatorial Guinea', 'Equatorial Guinea'), ('São Tomé and Príncipe', 'São Tomé and Príncipe')], default='Congo', max_length=64, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='country',
            field=models.CharField(choices=[('Congo', 'Congo'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Cameroon', 'Cameroon'), ('Gabon', 'Gabon'), ('Angola', 'Angola'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Equatorial Guinea', 'Equatorial Guinea'), ('São Tomé and Príncipe', 'São Tomé and Príncipe')], default='Congo', max_length=64, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(choices=[('Congo', 'Congo'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Cameroon', 'Cameroon'), ('Gabon', 'Gabon'), ('Angola', 'Angola'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Equatorial Guinea', 'Equatorial Guinea'), ('São Tomé and Príncipe', 'São Tomé and Príncipe')], default='Congo', max_length=64, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='location',
            field=models.CharField(blank=True, choices=[('Brazzaville', 'Brazzaville'), ('Pointe-Noire', 'Pointe-Noire'), ('Bouenza', 'Bouenza'), ('Niari', 'Niari'), ('Pool', 'Pool'), ('Plateaux', 'Plateaux'), ('Cuvette', 'Cuvette'), ('Cuvette-Ouest', 'Cuvette-Ouest'), ('Sangha', 'Sangha'), ('Likouala', 'Likouala'), ('Kouilou', 'Kouilou'), ('Lékoumou', 'Lékoumou'), ('Congo-Oubangui', 'Congo-Oubangui'), ('Nkéni-Alima', 'Nkéni-Alima'), ('Djoué-Léfini', 'Djoué-Léfini'), ('Internationale', 'Internationale')], default='Brazzaville', max_length=64, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='location',
            field=models.CharField(blank=True, choices=[('Brazzaville', 'Brazzaville'), ('Pointe-Noire', 'Pointe-Noire'), ('Bouenza', 'Bouenza'), ('Niari', 'Niari'), ('Pool', 'Pool'), ('Plateaux', 'Plateaux'), ('Cuvette', 'Cuvette'), ('Cuvette-Ouest', 'Cuvette-Ouest'), ('Sangha', 'Sangha'), ('Likouala', 'Likouala'), ('Kouilou', 'Kouilou'), ('Lékoumou', 'Lékoumou'), ('Congo-Oubangui', 'Congo-Oubangui'), ('Nkéni-Alima', 'Nkéni-Alima'), ('Djoué-Léfini', 'Djoué-Léfini'), ('Internationale', 'Internationale')], default='Brazzaville', max_length=64, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, choices=[('Brazzaville', 'Brazzaville'), ('Pointe-Noire', 'Pointe-Noire'), ('Bouenza', 'Bouenza'), ('Niari', 'Niari'), ('Pool', 'Pool'), ('Plateaux', 'Plateaux'), ('Cuvette', 'Cuvette'), ('Cuvette-Ouest', 'Cuvette-Ouest'), ('Sangha', 'Sangha'), ('Likouala', 'Likouala'), ('Kouilou', 'Kouilou'), ('Lékoumou', 'Lékoumou'), ('Congo-Oubangui', 'Congo-Oubangui'), ('Nkéni-Alima', 'Nkéni-Alima'), ('Djoué-Léfini', 'Djoué-Léfini'), ('Internationale', 'Internationale')], default='Brazzaville', max_length=64, verbose_name='Localisation'),
        ),
    ]
