# Generated by Django 6.0.4 on 2026-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0064_emailverification_country_siteuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pawapay', 'PawaPay'), ('kkiapay', 'KKiaPay'), ('orange_money', 'Orange Money'), ('wechat_pay', '微信支付'), ('alipay', '支付宝'), ('paypal', 'PayPal'), ('credit_card', 'Visa / Mastercard'), ('bank_transfer', '银行转账')], max_length=20, verbose_name='支付方式'),
        ),
    ]
