# Generated by Django 6.0.4 on 2026-07-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0065_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='country',
            field=models.CharField(choices=[('Congo', 'Congo'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Cameroon', 'Cameroon'), ('Gabon', 'Gabon'), ('Angola', 'Angola'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Equatorial Guinea', 'Equatorial Guinea'), ('São Tomé and Príncipe', 'São Tomé and Príncipe'), ('Benin', 'Benin'), ('Burkina Faso', 'Burkina Faso'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Senegal', 'Senegal'), ('Sierra Leone', 'Sierra Leone'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Lesotho', 'Lesotho'), ('France', 'France'), ('Turkey', 'Turkey'), ('China', 'China')], default='Congo', max_length=64, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='country',
            field=models.CharField(choices=[('Congo', 'Congo'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Cameroon', 'Cameroon'), ('Gabon', 'Gabon'), ('Angola', 'Angola'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Equatorial Guinea', 'Equatorial Guinea'), ('São Tomé and Príncipe', 'São Tomé and Príncipe'), ('Benin', 'Benin'), ('Burkina Faso', 'Burkina Faso'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Senegal', 'Senegal'), ('Sierra Leone', 'Sierra Leone'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Lesotho', 'Lesotho'), ('France', 'France'), ('Turkey', 'Turkey'), ('China', 'China')], default='Congo', max_length=64, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(choices=[('Congo', 'Congo'), ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Cameroon', 'Cameroon'), ('Gabon', 'Gabon'), ('Angola', 'Angola'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Equatorial Guinea', 'Equatorial Guinea'), ('São Tomé and Príncipe', 'São Tomé and Príncipe'), ('Benin', 'Benin'), ('Burkina Faso', 'Burkina Faso'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Senegal', 'Senegal'), ('Sierra Leone', 'Sierra Leone'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Lesotho', 'Lesotho'), ('France', 'France'), ('Turkey', 'Turkey'), ('China', 'China')], default='Congo', max_length=64, verbose_name='Pays'),
        ),
    ]
