# Generated by Django 6.0.4 on 2026-07-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0066_alter_emailverification_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='manager.vendor', verbose_name='所属商家'),
        ),
    ]
