# Generated by Django 6.0.4 on 2026-07-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0067_bookcategory_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新时间'),
        ),
    ]
