# Generated by Django 6.0.4 on 2026-07-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0068_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_zh_hans',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
