# Generated by Django 6.0.4 on 2026-07-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0069_author_name_widen'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='主管理员'),
        ),
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator')], default='admin', max_length=20, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='ManagerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator')], max_length=20, verbose_name='角色')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='邀请令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接受时间')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to='manager.manager', verbose_name='邀请人')),
            ],
            options={
                'verbose_name': '管理员邀请',
                'verbose_name_plural': '管理员邀请',
                'db_table': 'manager_invite',
                'ordering': ['-created_at'],
            },
        ),
    ]
