# Generated by Django 6.0.4 on 2026-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0071_backfill_primary_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivered_confirmed_by',
            field=models.CharField(blank=True, choices=[('buyer', 'Acheteur'), ('auto_timeout', 'Automatique'), ('admin', 'Admin'), ('digital', 'Numérique')], default='', max_length=20, verbose_name='Confirmée par'),
        ),
    ]
