# Generated by Django 6.0.4 on 2026-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0072_alter_shipment_delivered_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('physical', '实体书'), ('digital', '电子书'), ('both', '实体书+电子书')], default='physical', max_length=20, verbose_name='图书格式'),
        ),
    ]
